name: Build & Publish .NET Project

on:
  push:
    branches: [ master ]  # Ganti jika branch kamu beda

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Otomatis pakai versi terbaru .NET 8

    - name: Restore dependencies
      run: dotnet restore

    - name: Build all projects
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish main project
      run: dotnet publish src/ProductApi/ProductApi.csproj -c Release -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish
